export const defaultPack = {
  id: "pack_default",
  ownerId: "system",
  title: "Millionaire Questions",
  description: "A cinematic mix of pop culture, history, and science.",
  config: {
    currencySymbol: "$",
    amounts: [100, 200, 300, 500, 1000, 2000, 4000, 8000, 16000, 32000, 64000, 125000, 250000, 500000, 1000000],
    guaranteedLevels: [5, 10, 15],
    lifelines: [
      { key: "fifty_fifty", displayName: "50:50", enabled: true },
      { key: "ask_audience", displayName: "Ask the Audience", enabled: true },
      { key: "phone_friend", displayName: "Phone a Friend", enabled: true }
    ],
    messages: {
      winTitle: "Congratulations!",
      winMessage: "You are a millionaire!",
      loseTitle: "Game Over",
      loseMessage: "Better luck next time!",
      walkAwayTitle: "Well Played!",
      walkAwayMessage: "You walked away with:"
    }
  },
  questions: [
    {
      id: "q1",
      level: 1,
      type: "MCQ",
      promptText: "Which planet is known as the Red Planet?",
      options: { A: "Mars", B: "Venus", C: "Jupiter", D: "Mercury" },
      correctOption: "A",
      explanation: "Mars appears red due to iron oxide on its surface."
    },
    {
      id: "q2",
      level: 2,
      type: "MCQ",
      promptText: "What is the capital of Canada?",
      options: { A: "Toronto", B: "Vancouver", C: "Ottawa", D: "Montreal" },
      correctOption: "C"
    },
    {
      id: "q3",
      level: 3,
      type: "MCQ",
      promptText: "Which instrument has 88 keys?",
      options: { A: "Harp", B: "Piano", C: "Accordion", D: "Organ" },
      correctOption: "B"
    },
    {
      id: "q4",
      level: 4,
      type: "MCQ",
      promptText: "The Great Barrier Reef is located off the coast of which country?",
      options: { A: "Mexico", B: "Australia", C: "South Africa", D: "Brazil" },
      correctOption: "B"
    },
    {
      id: "q5",
      level: 5,
      type: "MCQ",
      promptText: "Which element has the chemical symbol O?",
      options: { A: "Gold", B: "Oxygen", C: "Osmium", D: "Tin" },
      correctOption: "B"
    },
    {
      id: "q6",
      level: 6,
      type: "MCQ",
      promptText: "Who wrote 'Pride and Prejudice'?",
      options: { A: "Charlotte Bronte", B: "Jane Austen", C: "Mary Shelley", D: "Emily Dickinson" },
      correctOption: "B"
    },
    {
      id: "q7",
      level: 7,
      type: "MCQ",
      promptText: "Which ocean is the largest on Earth?",
      options: { A: "Atlantic", B: "Indian", C: "Pacific", D: "Arctic" },
      correctOption: "C"
    },
    {
      id: "q8",
      level: 8,
      type: "MCQ",
      promptText: "What is the name of the first artificial satellite launched into space?",
      options: { A: "Voyager", B: "Sputnik", C: "Apollo", D: "Pioneer" },
      correctOption: "B"
    },
    {
      id: "q9",
      level: 9,
      type: "MCQ",
      promptText: "Which city hosted the 2012 Summer Olympics?",
      options: { A: "London", B: "Beijing", C: "Rio de Janeiro", D: "Tokyo" },
      correctOption: "A"
    },
    {
      id: "q10",
      level: 10,
      type: "MCQ",
      promptText: "What is the hardest natural substance?",
      options: { A: "Diamond", B: "Quartz", C: "Granite", D: "Platinum" },
      correctOption: "A"
    },
    {
      id: "q11",
      level: 11,
      type: "MCQ",
      promptText: "Which artist painted the ceiling of the Sistine Chapel?",
      options: { A: "Raphael", B: "Michelangelo", C: "Da Vinci", D: "Caravaggio" },
      correctOption: "B"
    },
    {
      id: "q12",
      level: 12,
      type: "MCQ",
      promptText: "What is the longest river in the world?",
      options: { A: "Amazon", B: "Nile", C: "Yangtze", D: "Mississippi" },
      correctOption: "B"
    },
    {
      id: "q13",
      level: 13,
      type: "MCQ",
      promptText: "Which gas makes up the majority of Earth's atmosphere?",
      options: { A: "Oxygen", B: "Nitrogen", C: "Carbon Dioxide", D: "Argon" },
      correctOption: "B"
    },
    {
      id: "q14",
      level: 14,
      type: "MCQ",
      promptText: "What is the largest desert in the world?",
      options: { A: "Sahara", B: "Gobi", C: "Antarctic Desert", D: "Arabian" },
      correctOption: "C"
    },
    {
      id: "q15",
      level: 15,
      type: "MCQ",
      promptText: "Which physicist developed the theory of general relativity?",
      options: { A: "Isaac Newton", B: "Albert Einstein", C: "Niels Bohr", D: "Marie Curie" },
      correctOption: "B"
    },
    {
      id: "fff1",
      level: 0,
      type: "FFF",
      promptText: "Fastest Finger: Which Surah is known as The Opening?",
      options: { A: "Al-Fatihah", B: "Al-Baqarah", C: "Al-Ikhlas", D: "Al-Kahf" },
      correctOption: "A"
    }
  ]
};

export const defaultCategoryDecks = [
  {
    id: "animals",
    title: "Animals",
    subtitle: "Animal Planet • Underwater Animals",
    questions: [
      { id: "animals_1", type: "MCQ", promptText: "Which mammal is known for echolocation?", options: { A: "Bat", B: "Otter", C: "Zebra", D: "Moose" }, correctOption: "A" },
      { id: "animals_2", type: "MCQ", promptText: "What is the fastest land animal?", options: { A: "Cheetah", B: "Pronghorn", C: "Lion", D: "Ostrich" }, correctOption: "A" },
      { id: "animals_3", type: "MCQ", promptText: "Which bird is famous for its colorful tail feathers and courtship display?", options: { A: "Peacock", B: "Flamingo", C: "Eagle", D: "Penguin" }, correctOption: "A" },
      { id: "animals_4", type: "MCQ", promptText: "A group of lions is called a:", options: { A: "Herd", B: "Pride", C: "School", D: "Pack" }, correctOption: "B" },
      { id: "animals_5", type: "MCQ", promptText: "Which animal is the largest on Earth?", options: { A: "African Elephant", B: "Blue Whale", C: "Giraffe", D: "Great White Shark" }, correctOption: "B" },
      { id: "animals_6", type: "MCQ", promptText: "What do you call a baby kangaroo?", options: { A: "Cub", B: "Joey", C: "Calf", D: "Fawn" }, correctOption: "B" },
      { id: "animals_7", type: "MCQ", promptText: "Which animal has the longest lifespan?", options: { A: "Galapagos Tortoise", B: "Elephant", C: "Blue Whale", D: "Parrot" }, correctOption: "A" },
      { id: "animals_8", type: "MCQ", promptText: "Which sea creature has eight arms and three hearts?", options: { A: "Squid", B: "Octopus", C: "Cuttlefish", D: "Jellyfish" }, correctOption: "B" },
      { id: "animals_9", type: "MCQ", promptText: "Which animal is known as the ship of the desert?", options: { A: "Horse", B: "Camel", C: "Llama", D: "Donkey" }, correctOption: "B" },
      { id: "animals_10", type: "MCQ", promptText: "Which bird cannot fly but can run very fast?", options: { A: "Penguin", B: "Ostrich", C: "Kiwi", D: "Emu" }, correctOption: "B" },
      { id: "animals_11", type: "MCQ", promptText: "What is the largest species of shark?", options: { A: "Great White", B: "Whale Shark", C: "Hammerhead", D: "Tiger Shark" }, correctOption: "B" },
      { id: "animals_12", type: "MCQ", promptText: "Which animal is known for changing its color to blend in?", options: { A: "Chameleon", B: "Iguana", C: "Gecko", D: "Anole" }, correctOption: "A" },
      { id: "animals_13", type: "MCQ", promptText: "What is a group of dolphins called?", options: { A: "Pod", B: "Flock", C: "Herd", D: "Colony" }, correctOption: "A" },
      { id: "animals_14", type: "MCQ", promptText: "Which animal has black and white stripes and lives in Africa?", options: { A: "Okapi", B: "Zebra", C: "Tapir", D: "Skunk" }, correctOption: "B" },
      { id: "animals_15", type: "MCQ", promptText: "Which insect produces honey?", options: { A: "Wasp", B: "Bee", C: "Ant", D: "Butterfly" }, correctOption: "B" },
      { id: "animals_16", type: "MCQ", promptText: "What is the largest species of bear?", options: { A: "Grizzly Bear", B: "Polar Bear", C: "Black Bear", D: "Panda" }, correctOption: "B" },
      { id: "animals_17", type: "MCQ", promptText: "Which animal is known for its trunk?", options: { A: "Elephant", B: "Rhinoceros", C: "Hippopotamus", D: "Walrus" }, correctOption: "A" },
      { id: "animals_18", type: "MCQ", promptText: "Which bird is a symbol of peace?", options: { A: "Dove", B: "Crow", C: "Raven", D: "Hawk" }, correctOption: "A" },
      { id: "animals_19", type: "MCQ", promptText: "Which animal sleeps standing up?", options: { A: "Horse", B: "Lion", C: "Tiger", D: "Gorilla" }, correctOption: "A" },
      { id: "animals_20", type: "MCQ", promptText: "What is the largest cat species?", options: { A: "Lion", B: "Leopard", C: "Tiger", D: "Jaguar" }, correctOption: "C" },
      { id: "animals_21", type: "MCQ", promptText: "Which animal has the most powerful bite among mammals?", options: { A: "Lion", B: "Hippo", C: "Hyena", D: "Bear" }, correctOption: "B" },
      { id: "animals_22", type: "MCQ", promptText: "Which marine animal is known for bioluminescence?", options: { A: "Sea Turtle", B: "Anglerfish", C: "Dolphin", D: "Manatee" }, correctOption: "B" },
      { id: "animals_23", type: "MCQ", promptText: "What is the largest species of penguin?", options: { A: "Emperor Penguin", B: "King Penguin", C: "Adelie Penguin", D: "Gentoo Penguin" }, correctOption: "A" },
      { id: "animals_24", type: "MCQ", promptText: "Which animal is famous for playing dead?", options: { A: "Raccoon", B: "Opossum", C: "Badger", D: "Fox" }, correctOption: "B" },
      { id: "animals_25", type: "MCQ", promptText: "Which fish is known for its ability to inflate?", options: { A: "Clownfish", B: "Pufferfish", C: "Angelfish", D: "Swordfish" }, correctOption: "B" },
      { id: "animals_26", type: "MCQ", promptText: "Which animal has a pouch and is native to Australia?", options: { A: "Koala", B: "Kangaroo", C: "Wombat", D: "All of these" }, correctOption: "D" },
      { id: "animals_27", type: "MCQ", promptText: "What do you call a group of whales?", options: { A: "Pod", B: "School", C: "Swarm", D: "Pride" }, correctOption: "A" },
      { id: "animals_28", type: "MCQ", promptText: "Which animal is known for its long neck?", options: { A: "Giraffe", B: "Moose", C: "Camel", D: "Llama" }, correctOption: "A" },
      { id: "animals_29", type: "MCQ", promptText: "Which sea creature moves by squirting water?", options: { A: "Octopus", B: "Seahorse", C: "Starfish", D: "Crab" }, correctOption: "A" },
      { id: "animals_30", type: "MCQ", promptText: "Which animal is the largest reptile?", options: { A: "Komodo Dragon", B: "Saltwater Crocodile", C: "Alligator", D: "Green Anaconda" }, correctOption: "B" },
      { id: "animals_31", type: "MCQ", promptText: "Which bird is known for mimicking sounds and speech?", options: { A: "Parrot", B: "Sparrow", C: "Robin", D: "Falcon" }, correctOption: "A" },
      { id: "animals_32", type: "MCQ", promptText: "What is the only mammal capable of true flight?", options: { A: "Flying Squirrel", B: "Bat", C: "Sugar Glider", D: "Colugo" }, correctOption: "B" },
      { id: "animals_33", type: "MCQ", promptText: "Which animal has the thickest fur?", options: { A: "Arctic Fox", B: "Sea Otter", C: "Polar Bear", D: "Wolverine" }, correctOption: "B" },
      { id: "animals_34", type: "MCQ", promptText: "Which animal is known for its black and white coat and bamboo diet?", options: { A: "Panda", B: "Zebra", C: "Skunk", D: "Badger" }, correctOption: "A" },
      { id: "animals_35", type: "MCQ", promptText: "Which animal has a prehensile tail?", options: { A: "Gorilla", B: "Spider Monkey", C: "Wolf", D: "Bear" }, correctOption: "B" },
      { id: "animals_36", type: "MCQ", promptText: "Which aquatic mammal is known for its tusks?", options: { A: "Walrus", B: "Seal", C: "Manatee", D: "Dugong" }, correctOption: "A" },
      { id: "animals_37", type: "MCQ", promptText: "Which animal can rotate its head up to 270 degrees?", options: { A: "Owl", B: "Eagle", C: "Falcon", D: "Hawk" }, correctOption: "A" },
      { id: "animals_38", type: "MCQ", promptText: "Which fish is famous for climbing waterfalls?", options: { A: "Salmon", B: "Trout", C: "Carp", D: "Catfish" }, correctOption: "A" },
      { id: "animals_39", type: "MCQ", promptText: "Which animal is known for its armor-like shell?", options: { A: "Armadillo", B: "Hedgehog", C: "Porcupine", D: "Pangolin" }, correctOption: "A" },
      { id: "animals_40", type: "MCQ", promptText: "Which sea creature has a crown of venomous spines?", options: { A: "Starfish", B: "Crown-of-thorns starfish", C: "Sea Urchin", D: "Sea Cucumber" }, correctOption: "B" },
      { id: "animals_41", type: "MCQ", promptText: "Which reptile is known for changing its skin color in water?", options: { A: "Crocodile", B: "Alligator", C: "Marine Iguana", D: "Sea Snake" }, correctOption: "C" },
      { id: "animals_42", type: "MCQ", promptText: "Which animal uses ink as a defense mechanism?", options: { A: "Octopus", B: "Seahorse", C: "Lobster", D: "Crab" }, correctOption: "A" },
      { id: "animals_43", type: "MCQ", promptText: "What is a group of frogs called?", options: { A: "Army", B: "Colony", C: "Swarm", D: "Huddle" }, correctOption: "A" },
      { id: "animals_44", type: "MCQ", promptText: "Which animal is known for its long tongue used to catch ants?", options: { A: "Anteater", B: "Aardvark", C: "Pangolin", D: "All of these" }, correctOption: "D" },
      { id: "animals_45", type: "MCQ", promptText: "Which bird can fly backward?", options: { A: "Hummingbird", B: "Swallow", C: "Sparrow", D: "Swift" }, correctOption: "A" }
    ]
  },
  {
    id: "geography",
    title: "Geography",
    subtitle: "States of America • Countries of the World • Cities Around the World",
    questions: [
      { id: "geo_1", type: "MCQ", promptText: "What is the capital of Japan?", options: { A: "Tokyo", B: "Kyoto", C: "Osaka", D: "Nagoya" }, correctOption: "A" },
      { id: "geo_2", type: "MCQ", promptText: "Which U.S. state is known as the Sunshine State?", options: { A: "California", B: "Florida", C: "Arizona", D: "Texas" }, correctOption: "B" },
      { id: "geo_3", type: "MCQ", promptText: "Which country has the largest population?", options: { A: "India", B: "United States", C: "China", D: "Indonesia" }, correctOption: "C" },
      { id: "geo_4", type: "MCQ", promptText: "What is the capital of Australia?", options: { A: "Sydney", B: "Melbourne", C: "Canberra", D: "Perth" }, correctOption: "C" },
      { id: "geo_5", type: "MCQ", promptText: "Which U.S. state is the largest by area?", options: { A: "Texas", B: "California", C: "Alaska", D: "Montana" }, correctOption: "C" },
      { id: "geo_6", type: "MCQ", promptText: "Which city is known as the Big Apple?", options: { A: "Los Angeles", B: "New York City", C: "Chicago", D: "Miami" }, correctOption: "B" },
      { id: "geo_7", type: "MCQ", promptText: "Which country is home to the Eiffel Tower?", options: { A: "Italy", B: "France", C: "Spain", D: "Belgium" }, correctOption: "B" },
      { id: "geo_8", type: "MCQ", promptText: "Which U.S. state has the Grand Canyon?", options: { A: "Utah", B: "Colorado", C: "Arizona", D: "Nevada" }, correctOption: "C" },
      { id: "geo_9", type: "MCQ", promptText: "What is the capital of Canada?", options: { A: "Toronto", B: "Montreal", C: "Ottawa", D: "Vancouver" }, correctOption: "C" },
      { id: "geo_10", type: "MCQ", promptText: "Which country is also a continent?", options: { A: "Australia", B: "Greenland", C: "Iceland", D: "Madagascar" }, correctOption: "A" },
      { id: "geo_11", type: "MCQ", promptText: "Which U.S. state is known as the Empire State?", options: { A: "New York", B: "New Jersey", C: "Pennsylvania", D: "Massachusetts" }, correctOption: "A" },
      { id: "geo_12", type: "MCQ", promptText: "What is the capital of Brazil?", options: { A: "Rio de Janeiro", B: "Brasilia", C: "Sao Paulo", D: "Salvador" }, correctOption: "B" },
      { id: "geo_13", type: "MCQ", promptText: "Which city is famous for the Colosseum?", options: { A: "Rome", B: "Athens", C: "Istanbul", D: "Cairo" }, correctOption: "A" },
      { id: "geo_14", type: "MCQ", promptText: "Which U.S. state is known as the Land of 10,000 Lakes?", options: { A: "Minnesota", B: "Michigan", C: "Wisconsin", D: "North Dakota" }, correctOption: "A" },
      { id: "geo_15", type: "MCQ", promptText: "Which country is the smallest by land area?", options: { A: "Monaco", B: "San Marino", C: "Vatican City", D: "Liechtenstein" }, correctOption: "C" },
      { id: "geo_16", type: "MCQ", promptText: "What is the capital of South Korea?", options: { A: "Busan", B: "Seoul", C: "Incheon", D: "Daegu" }, correctOption: "B" },
      { id: "geo_17", type: "MCQ", promptText: "Which U.S. state is known as the Lone Star State?", options: { A: "Texas", B: "Oklahoma", C: "Louisiana", D: "New Mexico" }, correctOption: "A" },
      { id: "geo_18", type: "MCQ", promptText: "Which country has the city of Marrakesh?", options: { A: "Morocco", B: "Egypt", C: "Tunisia", D: "Algeria" }, correctOption: "A" },
      { id: "geo_19", type: "MCQ", promptText: "Which city is known for the Opera House with sail-like roofs?", options: { A: "Auckland", B: "Sydney", C: "Cape Town", D: "Lisbon" }, correctOption: "B" },
      { id: "geo_20", type: "MCQ", promptText: "Which U.S. state has the most active volcanoes?", options: { A: "Hawaii", B: "Alaska", C: "California", D: "Washington" }, correctOption: "B" },
      { id: "geo_21", type: "MCQ", promptText: "What is the capital of Egypt?", options: { A: "Alexandria", B: "Cairo", C: "Giza", D: "Luxor" }, correctOption: "B" },
      { id: "geo_22", type: "MCQ", promptText: "Which country is famous for the fjords of Bergen and Oslo?", options: { A: "Norway", B: "Sweden", C: "Finland", D: "Denmark" }, correctOption: "A" },
      { id: "geo_23", type: "MCQ", promptText: "Which U.S. state is known for Mount Rushmore?", options: { A: "South Dakota", B: "North Dakota", C: "Wyoming", D: "Colorado" }, correctOption: "A" },
      { id: "geo_24", type: "MCQ", promptText: "What is the capital of Spain?", options: { A: "Barcelona", B: "Madrid", C: "Valencia", D: "Seville" }, correctOption: "B" },
      { id: "geo_25", type: "MCQ", promptText: "Which city is known as the City of Canals?", options: { A: "Amsterdam", B: "Venice", C: "Bruges", D: "Stockholm" }, correctOption: "B" },
      { id: "geo_26", type: "MCQ", promptText: "Which U.S. state has the nickname Peach State?", options: { A: "Georgia", B: "South Carolina", C: "Alabama", D: "Tennessee" }, correctOption: "A" },
      { id: "geo_27", type: "MCQ", promptText: "Which country is home to Machu Picchu?", options: { A: "Peru", B: "Chile", C: "Bolivia", D: "Ecuador" }, correctOption: "A" },
      { id: "geo_28", type: "MCQ", promptText: "What is the capital of Argentina?", options: { A: "Santiago", B: "Montevideo", C: "Buenos Aires", D: "Lima" }, correctOption: "C" },
      { id: "geo_29", type: "MCQ", promptText: "Which U.S. state is known as the Granite State?", options: { A: "New Hampshire", B: "Vermont", C: "Maine", D: "Rhode Island" }, correctOption: "A" },
      { id: "geo_30", type: "MCQ", promptText: "Which country has the city of Reykjavik?", options: { A: "Norway", B: "Iceland", C: "Ireland", D: "Greenland" }, correctOption: "B" },
      { id: "geo_31", type: "MCQ", promptText: "What is the capital of Kenya?", options: { A: "Nairobi", B: "Mombasa", C: "Kampala", D: "Dar es Salaam" }, correctOption: "A" },
      { id: "geo_32", type: "MCQ", promptText: "Which U.S. state is known as the Garden State?", options: { A: "New Jersey", B: "Connecticut", C: "Maryland", D: "Virginia" }, correctOption: "A" },
      { id: "geo_33", type: "MCQ", promptText: "Which country is home to the city of Timbuktu?", options: { A: "Mali", B: "Niger", C: "Chad", D: "Sudan" }, correctOption: "A" },
      { id: "geo_34", type: "MCQ", promptText: "Which city hosts the famous Christ the Redeemer statue?", options: { A: "Rio de Janeiro", B: "Lisbon", C: "Bogota", D: "Lima" }, correctOption: "A" },
      { id: "geo_35", type: "MCQ", promptText: "Which U.S. state is known for the Rocky Mountain National Park?", options: { A: "Colorado", B: "Utah", C: "Idaho", D: "Wyoming" }, correctOption: "A" },
      { id: "geo_36", type: "MCQ", promptText: "What is the capital of Thailand?", options: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, correctOption: "B" },
      { id: "geo_37", type: "MCQ", promptText: "Which country is home to the city of Dubrovnik?", options: { A: "Croatia", B: "Greece", C: "Italy", D: "Turkey" }, correctOption: "A" },
      { id: "geo_38", type: "MCQ", promptText: "Which U.S. state has the nickname Evergreen State?", options: { A: "Washington", B: "Oregon", C: "Maine", D: "Vermont" }, correctOption: "A" },
      { id: "geo_39", type: "MCQ", promptText: "Which country has the city of Cape Town?", options: { A: "Namibia", B: "South Africa", C: "Botswana", D: "Zimbabwe" }, correctOption: "B" },
      { id: "geo_40", type: "MCQ", promptText: "What is the capital of Germany?", options: { A: "Munich", B: "Hamburg", C: "Berlin", D: "Frankfurt" }, correctOption: "C" },
      { id: "geo_41", type: "MCQ", promptText: "Which U.S. state is known for the Bourbon Trail?", options: { A: "Kentucky", B: "Tennessee", C: "Missouri", D: "Indiana" }, correctOption: "A" },
      { id: "geo_42", type: "MCQ", promptText: "Which country is home to the city of Petra?", options: { A: "Jordan", B: "Israel", C: "Lebanon", D: "Syria" }, correctOption: "A" },
      { id: "geo_43", type: "MCQ", promptText: "Which U.S. state is known for the city of New Orleans?", options: { A: "Louisiana", B: "Mississippi", C: "Alabama", D: "Arkansas" }, correctOption: "A" },
      { id: "geo_44", type: "MCQ", promptText: "What is the capital of Norway?", options: { A: "Oslo", B: "Bergen", C: "Trondheim", D: "Stavanger" }, correctOption: "A" },
      { id: "geo_45", type: "MCQ", promptText: "Which city is known as the Windy City?", options: { A: "Chicago", B: "Boston", C: "Seattle", D: "Denver" }, correctOption: "A" }
    ]
  },
  {
    id: "science_nature",
    title: "Science & Nature",
    subtitle: "Dinosaurs • Space",
    questions: [
      { id: "sci_1", type: "MCQ", promptText: "Which planet is known as the Red Planet?", options: { A: "Mars", B: "Venus", C: "Jupiter", D: "Mercury" }, correctOption: "A" },
      { id: "sci_2", type: "MCQ", promptText: "What is the closest star to Earth?", options: { A: "Proxima Centauri", B: "Sirius", C: "The Sun", D: "Vega" }, correctOption: "C" },
      { id: "sci_3", type: "MCQ", promptText: "What is the largest planet in our solar system?", options: { A: "Saturn", B: "Jupiter", C: "Neptune", D: "Uranus" }, correctOption: "B" },
      { id: "sci_4", type: "MCQ", promptText: "Which dinosaur is known for its three horns?", options: { A: "Stegosaurus", B: "Triceratops", C: "Tyrannosaurus", D: "Velociraptor" }, correctOption: "B" },
      { id: "sci_5", type: "MCQ", promptText: "What is the name of Earth's natural satellite?", options: { A: "Phobos", B: "Moon", C: "Europa", D: "Titan" }, correctOption: "B" },
      { id: "sci_6", type: "MCQ", promptText: "Which planet is famous for its rings?", options: { A: "Jupiter", B: "Saturn", C: "Uranus", D: "Neptune" }, correctOption: "B" },
      { id: "sci_7", type: "MCQ", promptText: "Which dinosaur had plates along its back?", options: { A: "Brachiosaurus", B: "Stegosaurus", C: "Ankylosaurus", D: "Allosaurus" }, correctOption: "B" },
      { id: "sci_8", type: "MCQ", promptText: "What is the hottest planet in our solar system?", options: { A: "Mercury", B: "Venus", C: "Mars", D: "Jupiter" }, correctOption: "B" },
      { id: "sci_9", type: "MCQ", promptText: "Which dinosaur is often called the king of the dinosaurs?", options: { A: "Tyrannosaurus rex", B: "Spinosaurus", C: "Giganotosaurus", D: "Allosaurus" }, correctOption: "A" },
      { id: "sci_10", type: "MCQ", promptText: "What is the name of the galaxy we live in?", options: { A: "Andromeda", B: "Milky Way", C: "Sombrero", D: "Whirlpool" }, correctOption: "B" },
      { id: "sci_11", type: "MCQ", promptText: "Which planet has the Great Red Spot?", options: { A: "Jupiter", B: "Saturn", C: "Neptune", D: "Uranus" }, correctOption: "A" },
      { id: "sci_12", type: "MCQ", promptText: "Which dinosaur was known for its long neck?", options: { A: "Velociraptor", B: "Brachiosaurus", C: "Ankylosaurus", D: "Dilophosaurus" }, correctOption: "B" },
      { id: "sci_13", type: "MCQ", promptText: "What is the largest moon in the solar system?", options: { A: "Europa", B: "Titan", C: "Ganymede", D: "Io" }, correctOption: "C" },
      { id: "sci_14", type: "MCQ", promptText: "Which planet is known for its blue color due to methane?", options: { A: "Neptune", B: "Uranus", C: "Both A and B", D: "Earth" }, correctOption: "C" },
      { id: "sci_15", type: "MCQ", promptText: "Which dinosaur had a dome-shaped skull?", options: { A: "Pachycephalosaurus", B: "Parasaurolophus", C: "Stegosaurus", D: "Ceratosaurus" }, correctOption: "A" },
      { id: "sci_16", type: "MCQ", promptText: "What is the term for a star explosion?", options: { A: "Nebula", B: "Supernova", C: "Comet", D: "Asteroid" }, correctOption: "B" },
      { id: "sci_17", type: "MCQ", promptText: "Which dinosaur had a club-like tail?", options: { A: "Ankylosaurus", B: "Triceratops", C: "Iguanodon", D: "Gallimimus" }, correctOption: "A" },
      { id: "sci_18", type: "MCQ", promptText: "Which planet is farthest from the Sun?", options: { A: "Neptune", B: "Uranus", C: "Saturn", D: "Pluto" }, correctOption: "A" },
      { id: "sci_19", type: "MCQ", promptText: "Which dinosaur is known for its sickle-shaped claw?", options: { A: "Velociraptor", B: "Diplodocus", C: "Triceratops", D: "Apatosaurus" }, correctOption: "A" },
      { id: "sci_20", type: "MCQ", promptText: "Which planet has a day longer than its year?", options: { A: "Mercury", B: "Venus", C: "Mars", D: "Jupiter" }, correctOption: "B" },
      { id: "sci_21", type: "MCQ", promptText: "What is the name of Mars' largest moon?", options: { A: "Phobos", B: "Deimos", C: "Io", D: "Europa" }, correctOption: "A" },
      { id: "sci_22", type: "MCQ", promptText: "Which dinosaur was a duck-billed herbivore?", options: { A: "Hadrosaurus", B: "Spinosaurus", C: "Therizinosaurus", D: "Carnotaurus" }, correctOption: "A" },
      { id: "sci_23", type: "MCQ", promptText: "What is the asteroid belt located between?", options: { A: "Earth and Mars", B: "Mars and Jupiter", C: "Jupiter and Saturn", D: "Saturn and Uranus" }, correctOption: "B" },
      { id: "sci_24", type: "MCQ", promptText: "Which dinosaur is famous for its sail-like spine?", options: { A: "Stegosaurus", B: "Spinosaurus", C: "Allosaurus", D: "Iguanodon" }, correctOption: "B" },
      { id: "sci_25", type: "MCQ", promptText: "Which planet is known for its tilted axis?", options: { A: "Uranus", B: "Neptune", C: "Jupiter", D: "Mars" }, correctOption: "A" },
      { id: "sci_26", type: "MCQ", promptText: "What is the name of the first man-made satellite?", options: { A: "Explorer 1", B: "Sputnik 1", C: "Voyager 1", D: "Apollo 11" }, correctOption: "B" },
      { id: "sci_27", type: "MCQ", promptText: "Which dinosaur had a crest shaped like a tube?", options: { A: "Parasaurolophus", B: "Corythosaurus", C: "Triceratops", D: "Ankylosaurus" }, correctOption: "A" },
      { id: "sci_28", type: "MCQ", promptText: "Which planet is called Earth's twin?", options: { A: "Venus", B: "Mars", C: "Mercury", D: "Uranus" }, correctOption: "A" },
      { id: "sci_29", type: "MCQ", promptText: "Which dinosaur is known for its armor plates and spikes?", options: { A: "Stegosaurus", B: "Brachiosaurus", C: "Dilophosaurus", D: "Compsognathus" }, correctOption: "A" },
      { id: "sci_30", type: "MCQ", promptText: "What is the largest asteroid in the asteroid belt?", options: { A: "Vesta", B: "Pallas", C: "Ceres", D: "Hygiea" }, correctOption: "C" },
      { id: "sci_31", type: "MCQ", promptText: "Which dinosaur was known for its long, whip-like tail?", options: { A: "Diplodocus", B: "Spinosaurus", C: "Theropod", D: "Carnotaurus" }, correctOption: "A" },
      { id: "sci_32", type: "MCQ", promptText: "What is the name of NASA's most famous space telescope?", options: { A: "Hubble", B: "Kepler", C: "Spitzer", D: "Chandra" }, correctOption: "A" },
      { id: "sci_33", type: "MCQ", promptText: "Which dinosaur was known for its small size and speed?", options: { A: "Velociraptor", B: "T. rex", C: "Brachiosaurus", D: "Ankylosaurus" }, correctOption: "A" },
      { id: "sci_34", type: "MCQ", promptText: "Which planet has the most moons?", options: { A: "Saturn", B: "Jupiter", C: "Uranus", D: "Neptune" }, correctOption: "A" },
      { id: "sci_35", type: "MCQ", promptText: "What is the name of the boundary around a black hole?", options: { A: "Singularity", B: "Event Horizon", C: "Accretion Disk", D: "Nebula" }, correctOption: "B" },
      { id: "sci_36", type: "MCQ", promptText: "Which dinosaur had a thick, bony head used for head-butting?", options: { A: "Pachycephalosaurus", B: "Iguanodon", C: "Gallimimus", D: "Baryonyx" }, correctOption: "A" },
      { id: "sci_37", type: "MCQ", promptText: "Which planet is known for its Great Dark Spot?", options: { A: "Neptune", B: "Uranus", C: "Saturn", D: "Jupiter" }, correctOption: "A" },
      { id: "sci_38", type: "MCQ", promptText: "Which dinosaur was a massive herbivore with a long tail and neck?", options: { A: "Apatosaurus", B: "Allosaurus", C: "Carnotaurus", D: "Ceratosaurus" }, correctOption: "A" },
      { id: "sci_39", type: "MCQ", promptText: "What is the name of Earth's atmosphere layer where weather occurs?", options: { A: "Stratosphere", B: "Troposphere", C: "Mesosphere", D: "Thermosphere" }, correctOption: "B" },
      { id: "sci_40", type: "MCQ", promptText: "Which planet is known as the Morning Star?", options: { A: "Mercury", B: "Venus", C: "Mars", D: "Jupiter" }, correctOption: "B" },
      { id: "sci_41", type: "MCQ", promptText: "Which dinosaur had a beak and lived in herds?", options: { A: "Triceratops", B: "Hadrosaurus", C: "Allosaurus", D: "Stegosaurus" }, correctOption: "B" },
      { id: "sci_42", type: "MCQ", promptText: "Which space probe has traveled the farthest from Earth?", options: { A: "Voyager 1", B: "Pioneer 10", C: "New Horizons", D: "Voyager 2" }, correctOption: "A" },
      { id: "sci_43", type: "MCQ", promptText: "Which dinosaur is known for its long, curved claw on each hand?", options: { A: "Therizinosaurus", B: "Velociraptor", C: "Triceratops", D: "Stegosaurus" }, correctOption: "A" },
      { id: "sci_44", type: "MCQ", promptText: "What is the name of the closest galaxy to the Milky Way?", options: { A: "Andromeda", B: "Triangulum", C: "Sombrero", D: "Whirlpool" }, correctOption: "A" },
      { id: "sci_45", type: "MCQ", promptText: "Which dinosaur was a massive predator larger than T. rex?", options: { A: "Spinosaurus", B: "Allosaurus", C: "Utahraptor", D: "Dilophosaurus" }, correctOption: "A" }
    ]
  },
  {
    id: "kids_gk",
    title: "Kids General Knowledge",
    subtitle: "Kids Quiz",
    questions: [
      { id: "kids_1", type: "MCQ", promptText: "How many days are in a week?", options: { A: "7", B: "5", C: "6", D: "8" }, correctOption: "A" },
      { id: "kids_2", type: "MCQ", promptText: "Which color is the sky on a clear day?", options: { A: "Blue", B: "Green", C: "Red", D: "Purple" }, correctOption: "A" },
      { id: "kids_3", type: "MCQ", promptText: "Which animal says \"meow\"?", options: { A: "Dog", B: "Cat", C: "Cow", D: "Sheep" }, correctOption: "B" },
      { id: "kids_4", type: "MCQ", promptText: "What do bees make?", options: { A: "Milk", B: "Honey", C: "Bread", D: "Cheese" }, correctOption: "B" },
      { id: "kids_5", type: "MCQ", promptText: "Which planet do we live on?", image: "assets/questions/earth.jpg", imageAlt: "Earth from space", options: { A: "Mars", B: "Earth", C: "Jupiter", D: "Venus" }, correctOption: "B" },
      { id: "kids_6", type: "MCQ", promptText: "How many legs does a spider have?", options: { A: "6", B: "8", C: "10", D: "12" }, correctOption: "B" },
      { id: "kids_7", type: "MCQ", promptText: "Which shape has three sides?", options: { A: "Square", B: "Triangle", C: "Circle", D: "Rectangle" }, correctOption: "B" },
      { id: "kids_8", type: "MCQ", promptText: "Which season is the coldest?", options: { A: "Spring", B: "Summer", C: "Autumn", D: "Winter" }, correctOption: "D" },
      { id: "kids_9", type: "MCQ", promptText: "What is H2O commonly called?", options: { A: "Salt", B: "Water", C: "Oxygen", D: "Sugar" }, correctOption: "B" },
      { id: "kids_10", type: "MCQ", promptText: "Which fruit is yellow and curved?", image: "assets/questions/banana.jpg", imageAlt: "Banana", options: { A: "Apple", B: "Banana", C: "Orange", D: "Grape" }, correctOption: "B" },
      { id: "kids_11", type: "MCQ", promptText: "Which animal is known as the king of the jungle?", image: "assets/questions/lion.jpg", imageAlt: "Lion", options: { A: "Elephant", B: "Lion", C: "Giraffe", D: "Zebra" }, correctOption: "B" },
      { id: "kids_12", type: "MCQ", promptText: "What do plants need to grow?", options: { A: "Sunlight", B: "Candy", C: "Snow", D: "Sand" }, correctOption: "A" },
      { id: "kids_13", type: "MCQ", promptText: "Which month comes after June?", options: { A: "May", B: "July", C: "August", D: "April" }, correctOption: "B" },
      { id: "kids_14", type: "MCQ", promptText: "How many hours are in a day?", options: { A: "12", B: "18", C: "24", D: "30" }, correctOption: "C" },
      { id: "kids_15", type: "MCQ", promptText: "Which tool tells time?", options: { A: "Clock", B: "Ruler", C: "Spoon", D: "Brush" }, correctOption: "A" },
      { id: "kids_16", type: "MCQ", promptText: "Which insect makes a hive?", options: { A: "Butterfly", B: "Bee", C: "Ant", D: "Spider" }, correctOption: "B" },
      { id: "kids_17", type: "MCQ", promptText: "What is the opposite of hot?", options: { A: "Cold", B: "Wet", C: "Light", D: "Soft" }, correctOption: "A" },
      { id: "kids_18", type: "MCQ", promptText: "Which body part do you hear with?", options: { A: "Eye", B: "Nose", C: "Ear", D: "Hand" }, correctOption: "C" },
      { id: "kids_19", type: "MCQ", promptText: "Which ocean is the largest?", options: { A: "Atlantic", B: "Indian", C: "Pacific", D: "Arctic" }, correctOption: "C" },
      { id: "kids_20", type: "MCQ", promptText: "Which animal lives in water and has gills?", options: { A: "Dog", B: "Fish", C: "Cat", D: "Bird" }, correctOption: "B" },
      { id: "kids_21", type: "MCQ", promptText: "What color are stop signs?", options: { A: "Green", B: "Yellow", C: "Red", D: "Blue" }, correctOption: "C" },
      { id: "kids_22", type: "MCQ", promptText: "Which planet is closest to the Sun?", options: { A: "Mercury", B: "Earth", C: "Mars", D: "Jupiter" }, correctOption: "A" },
      { id: "kids_23", type: "MCQ", promptText: "Which object is used to write?", image: "assets/questions/pencil.jpg", imageAlt: "Pencil", options: { A: "Fork", B: "Pencil", C: "Plate", D: "Cup" }, correctOption: "B" },
      { id: "kids_24", type: "MCQ", promptText: "How many continents are there?", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "C" },
      { id: "kids_25", type: "MCQ", promptText: "Which animal carries its baby in a pouch?", options: { A: "Kangaroo", B: "Tiger", C: "Horse", D: "Sheep" }, correctOption: "A" },
      { id: "kids_26", type: "MCQ", promptText: "Which instrument has black and white keys?", options: { A: "Drum", B: "Piano", C: "Flute", D: "Guitar" }, correctOption: "B" },
      { id: "kids_27", type: "MCQ", promptText: "Which holiday uses a tree and gifts?", options: { A: "Easter", B: "Christmas", C: "Halloween", D: "Thanksgiving" }, correctOption: "B" },
      { id: "kids_28", type: "MCQ", promptText: "What do you call a baby dog?", options: { A: "Kitten", B: "Puppy", C: "Calf", D: "Foal" }, correctOption: "B" },
      { id: "kids_29", type: "MCQ", promptText: "Which shape is round?", options: { A: "Circle", B: "Triangle", C: "Square", D: "Rectangle" }, correctOption: "A" },
      { id: "kids_30", type: "MCQ", promptText: "How many sides does a square have?", options: { A: "3", B: "4", C: "5", D: "6" }, correctOption: "B" },
      { id: "kids_31", type: "MCQ", promptText: "Which animal is the fastest land animal?", options: { A: "Cheetah", B: "Lion", C: "Elephant", D: "Horse" }, correctOption: "A" },
      { id: "kids_32", type: "MCQ", promptText: "Which animal gives us milk?", options: { A: "Cow", B: "Chicken", C: "Dog", D: "Cat" }, correctOption: "A" },
      { id: "kids_33", type: "MCQ", promptText: "What do you call frozen water?", options: { A: "Ice", B: "Steam", C: "Sand", D: "Clay" }, correctOption: "A" },
      { id: "kids_34", type: "MCQ", promptText: "Which planet is known as the Red Planet?", options: { A: "Mars", B: "Venus", C: "Earth", D: "Mercury" }, correctOption: "A" },
      { id: "kids_35", type: "MCQ", promptText: "Which is used to go up floors in a building?", options: { A: "Elevator", B: "Ramp", C: "Slide", D: "Bridge" }, correctOption: "A" },
      { id: "kids_36", type: "MCQ", promptText: "Which animal has a long trunk?", options: { A: "Elephant", B: "Hippo", C: "Rhino", D: "Gorilla" }, correctOption: "A" },
      { id: "kids_37", type: "MCQ", promptText: "What do you call the person who teaches in school?", options: { A: "Pilot", B: "Teacher", C: "Baker", D: "Farmer" }, correctOption: "B" },
      { id: "kids_38", type: "MCQ", promptText: "Which is a common way to travel on rails?", options: { A: "Train", B: "Boat", C: "Bike", D: "Plane" }, correctOption: "A" },
      { id: "kids_39", type: "MCQ", promptText: "Which vegetable is orange and crunchy?", options: { A: "Carrot", B: "Potato", C: "Lettuce", D: "Pepper" }, correctOption: "A" },
      { id: "kids_40", type: "MCQ", promptText: "Which shape has four equal sides?", options: { A: "Square", B: "Triangle", C: "Oval", D: "Pentagon" }, correctOption: "A" },
      { id: "kids_41", type: "MCQ", promptText: "Which animal is the tallest?", options: { A: "Giraffe", B: "Camel", C: "Horse", D: "Bear" }, correctOption: "A" },
      { id: "kids_42", type: "MCQ", promptText: "Which planet has rings?", options: { A: "Saturn", B: "Mars", C: "Mercury", D: "Earth" }, correctOption: "A" },
      { id: "kids_43", type: "MCQ", promptText: "Which part of a plant is usually green?", options: { A: "Leaf", B: "Root", C: "Stem", D: "Seed" }, correctOption: "A" },
      { id: "kids_44", type: "MCQ", promptText: "Which device is used to take photos?", options: { A: "Camera", B: "Hammer", C: "Lantern", D: "Whistle" }, correctOption: "A" },
      { id: "kids_45", type: "MCQ", promptText: "Which fruit is shown?", image: "assets/questions/apple.jpg", imageAlt: "Apple", options: { A: "Apple", B: "Orange", C: "Pear", D: "Peach" }, correctOption: "A" }
    ]
  },
  {
    id: "mathematics",
    title: "Mathematics",
    subtitle: "Numbers • Algebra • Geometry • Probability",
    questions: [
      { id: "math_1", type: "MCQ", promptText: "What is 2 + 3?", options: { A: "4", B: "5", C: "6", D: "7" }, correctOption: "B" },
      { id: "math_2", type: "MCQ", promptText: "What is 10 - 4?", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "B" },
      { id: "math_3", type: "MCQ", promptText: "What is 6 x 7?", options: { A: "36", B: "40", C: "42", D: "48" }, correctOption: "C" },
      { id: "math_4", type: "MCQ", promptText: "What is 12 divided by 3?", options: { A: "3", B: "4", C: "5", D: "6" }, correctOption: "B" },
      { id: "math_5", type: "MCQ", promptText: "What is 5 squared?", options: { A: "10", B: "15", C: "20", D: "25" }, correctOption: "D" },
      { id: "math_6", type: "MCQ", promptText: "Simplify 6/12.", options: { A: "1/3", B: "1/2", C: "2/3", D: "3/4" }, correctOption: "B" },
      { id: "math_7", type: "MCQ", promptText: "Which fraction equals 0.5?", options: { A: "1/3", B: "1/2", C: "2/3", D: "3/4" }, correctOption: "B" },
      { id: "math_8", type: "MCQ", promptText: "What is the perimeter of a square with side 4?", options: { A: "8", B: "12", C: "16", D: "20" }, correctOption: "C" },
      { id: "math_9", type: "MCQ", promptText: "What is the area of a rectangle 3 by 5?", options: { A: "8", B: "10", C: "12", D: "15" }, correctOption: "D" },
      { id: "math_10", type: "MCQ", promptText: "What is the sum of angles in a triangle?", options: { A: "90", B: "120", C: "180", D: "360" }, correctOption: "C" },
      { id: "math_11", type: "MCQ", promptText: "Which number is prime?", options: { A: "9", B: "12", C: "15", D: "17" }, correctOption: "D" },
      { id: "math_12", type: "MCQ", promptText: "What is the LCM of 4 and 6?", options: { A: "8", B: "10", C: "12", D: "24" }, correctOption: "C" },
      { id: "math_13", type: "MCQ", promptText: "What is the GCD of 12 and 18?", options: { A: "3", B: "6", C: "9", D: "12" }, correctOption: "B" },
      { id: "math_14", type: "MCQ", promptText: "Solve: x + 5 = 12.", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "C" },
      { id: "math_15", type: "MCQ", promptText: "Solve: 3x = 15.", options: { A: "3", B: "4", C: "5", D: "6" }, correctOption: "C" },
      { id: "math_16", type: "MCQ", promptText: "Solve: 2x + 3 = 11.", options: { A: "3", B: "4", C: "5", D: "6" }, correctOption: "B" },
      { id: "math_17", type: "MCQ", promptText: "Solve: 5x - 10 = 0.", options: { A: "1", B: "2", C: "3", D: "4" }, correctOption: "B" },
      { id: "math_18", type: "MCQ", promptText: "What is 2 to the power of 3?", options: { A: "6", B: "7", C: "8", D: "9" }, correctOption: "C" },
      { id: "math_19", type: "MCQ", promptText: "What is the square root of 81?", options: { A: "7", B: "8", C: "9", D: "10" }, correctOption: "C" },
      { id: "math_20", type: "MCQ", promptText: "A ratio is 2:3 and the total is 25. What is the 2-part?", options: { A: "8", B: "9", C: "10", D: "12" }, correctOption: "C" },
      { id: "math_21", type: "MCQ", promptText: "What is 20% of 50?", options: { A: "5", B: "10", C: "15", D: "20" }, correctOption: "B" },
      { id: "math_22", type: "MCQ", promptText: "What is the probability of heads on a fair coin?", options: { A: "1/4", B: "1/3", C: "1/2", D: "3/4" }, correctOption: "C" },
      { id: "math_23", type: "MCQ", promptText: "What is the probability of rolling a 6 on a fair die?", options: { A: "1/2", B: "1/3", C: "1/6", D: "1/12" }, correctOption: "C" },
      { id: "math_24", type: "MCQ", promptText: "What is the mean of 2, 4, 6, 8?", options: { A: "4", B: "5", C: "6", D: "7" }, correctOption: "B" },
      { id: "math_25", type: "MCQ", promptText: "What is the median of 1, 3, 5, 7, 9?", options: { A: "3", B: "5", C: "7", D: "9" }, correctOption: "B" },
      { id: "math_26", type: "MCQ", promptText: "What is the mode of 2, 2, 3, 4?", options: { A: "2", B: "3", C: "4", D: "None" }, correctOption: "A" },
      { id: "math_27", type: "MCQ", promptText: "Convert 3/4 to a decimal.", options: { A: "0.25", B: "0.5", C: "0.75", D: "0.9" }, correctOption: "C" },
      { id: "math_28", type: "MCQ", promptText: "Simplify 12/16.", options: { A: "1/2", B: "3/4", C: "2/3", D: "4/5" }, correctOption: "B" },
      { id: "math_29", type: "MCQ", promptText: "Which formula gives the area of a circle?", options: { A: "pi r^2", B: "2 pi r", C: "r^2", D: "pi r" }, correctOption: "A" },
      { id: "math_30", type: "MCQ", promptText: "A triangle with sides 3, 4, 5 is:", options: { A: "Isosceles", B: "Equilateral", C: "Right triangle", D: "Obtuse" }, correctOption: "C" },
      { id: "math_31", type: "MCQ", promptText: "If a and b are positive and a > b, then a - b is:", options: { A: "Negative", B: "Zero", C: "Positive", D: "Undefined" }, correctOption: "C" },
      { id: "math_32", type: "MCQ", promptText: "Solve: 2x - 4 = 10.", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "B" },
      { id: "math_33", type: "MCQ", promptText: "What is 0.25 as a fraction?", options: { A: "1/2", B: "1/3", C: "1/4", D: "3/4" }, correctOption: "C" },
      { id: "math_34", type: "MCQ", promptText: "What is log10(100)?", options: { A: "1", B: "2", C: "3", D: "4" }, correctOption: "B" },
      { id: "math_35", type: "MCQ", promptText: "What is the slope of y = 2x + 3?", options: { A: "1", B: "2", C: "3", D: "4" }, correctOption: "B" },
      { id: "math_36", type: "MCQ", promptText: "If f(x) = x^2, what is f(3)?", options: { A: "6", B: "9", C: "12", D: "15" }, correctOption: "B" },
      { id: "math_37", type: "MCQ", promptText: "What is the sum of the first 10 natural numbers?", options: { A: "45", B: "50", C: "55", D: "60" }, correctOption: "C" },
      { id: "math_38", type: "MCQ", promptText: "How many degrees are in a straight line?", options: { A: "90", B: "120", C: "180", D: "360" }, correctOption: "C" },
      { id: "math_39", type: "MCQ", promptText: "Which number is irrational?", options: { A: "3/4", B: "0.2", C: "sqrt(2)", D: "5" }, correctOption: "C" },
      { id: "math_40", type: "MCQ", promptText: "In a right triangle, a^2 + b^2 = ?", options: { A: "c^2", B: "2c", C: "ab", D: "c/2" }, correctOption: "A" },
      { id: "math_41", type: "MCQ", promptText: "If probability is 0.2, what percent is that?", options: { A: "2%", B: "10%", C: "20%", D: "50%" }, correctOption: "C" },
      { id: "math_42", type: "MCQ", promptText: "Solve: x^2 = 49.", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "C" },
      { id: "math_43", type: "MCQ", promptText: "What is the expected value of a fair six-sided die?", options: { A: "2.5", B: "3", C: "3.5", D: "4" }, correctOption: "C" },
      { id: "math_44", type: "MCQ", promptText: "Which angle is greater than 90 degrees?", options: { A: "Acute", B: "Right", C: "Obtuse", D: "Straight" }, correctOption: "C" },
      { id: "math_45", type: "MCQ", promptText: "How many sides does a hexagon have?", options: { A: "5", B: "6", C: "7", D: "8" }, correctOption: "B" }
    ]
  },
  {
    id: "aptitude",
    title: "Aptitude",
    subtitle: "Verbal • Numerical • Abstract • Logic • Patterns",
    questions: [
      { id: "apt_1", type: "MCQ", promptText: "Find the next number: 2, 4, 6, 8, ?", options: { A: "9", B: "10", C: "11", D: "12" }, correctOption: "B" },
      { id: "apt_2", type: "MCQ", promptText: "Find the next number: 1, 1, 2, 3, 5, ?", options: { A: "6", B: "7", C: "8", D: "9" }, correctOption: "C" },
      { id: "apt_3", type: "MCQ", promptText: "Which word does not belong?", options: { A: "Apple", B: "Banana", C: "Carrot", D: "Grape" }, correctOption: "C" },
      { id: "apt_4", type: "MCQ", promptText: "Choose the synonym of \"happy\".", options: { A: "Sad", B: "Angry", C: "Joyful", D: "Tired" }, correctOption: "C" },
      { id: "apt_5", type: "MCQ", promptText: "Choose the antonym of \"increase\".", options: { A: "Grow", B: "Decrease", C: "Add", D: "Raise" }, correctOption: "B" },
      { id: "apt_6", type: "MCQ", promptText: "If all bloops are razzies and all razzies are lazzies, then all bloops are:", options: { A: "Lazzies", B: "Razzies", C: "Zazzies", D: "Fizzies" }, correctOption: "A" },
      { id: "apt_7", type: "MCQ", promptText: "Find the next letter: A, C, E, G, ?", options: { A: "H", B: "I", C: "J", D: "K" }, correctOption: "B" },
      { id: "apt_8", type: "MCQ", promptText: "Which word is a palindrome?", options: { A: "Level", B: "Apple", C: "Bridge", D: "House" }, correctOption: "A" },
      { id: "apt_9", type: "MCQ", promptText: "Which fraction is larger?", options: { A: "2/3", B: "3/5", C: "1/2", D: "4/9" }, correctOption: "A" },
      { id: "apt_10", type: "MCQ", promptText: "If 5 machines make 5 items in 5 minutes, how many items can 5 machines make in 10 minutes?", options: { A: "5", B: "8", C: "10", D: "15" }, correctOption: "C" },
      { id: "apt_11", type: "MCQ", promptText: "Find the next number: 3, 6, 12, 24, ?", options: { A: "36", B: "40", C: "48", D: "60" }, correctOption: "C" },
      { id: "apt_12", type: "MCQ", promptText: "Which comes next: 10, 20, 40, 80, ?", options: { A: "100", B: "120", C: "160", D: "200" }, correctOption: "C" },
      { id: "apt_13", type: "MCQ", promptText: "If today is Tuesday, what day is it in 3 days?", options: { A: "Wednesday", B: "Thursday", C: "Friday", D: "Saturday" }, correctOption: "C" },
      { id: "apt_14", type: "MCQ", promptText: "Choose the odd one out.", options: { A: "Square", B: "Circle", C: "Triangle", D: "Blue" }, correctOption: "D" },
      { id: "apt_15", type: "MCQ", promptText: "Find the next number: 1, 4, 9, 16, ?", options: { A: "20", B: "25", C: "30", D: "36" }, correctOption: "B" },
      { id: "apt_16", type: "MCQ", promptText: "Which word completes the analogy: Bird is to Fly as Fish is to ?", options: { A: "Swim", B: "Run", C: "Jump", D: "Crawl" }, correctOption: "A" },
      { id: "apt_17", type: "MCQ", promptText: "If some cats are pets and all pets are loved, then some cats are:", options: { A: "Loved", B: "Wild", C: "Hungry", D: "Fast" }, correctOption: "A" },
      { id: "apt_18", type: "MCQ", promptText: "Choose the word that means the same as \"quick\".", options: { A: "Slow", B: "Rapid", C: "Late", D: "Lazy" }, correctOption: "B" },
      { id: "apt_19", type: "MCQ", promptText: "Find the next number: 5, 9, 13, 17, ?", options: { A: "19", B: "21", C: "23", D: "25" }, correctOption: "B" },
      { id: "apt_20", type: "MCQ", promptText: "Which is a valid conclusion? All squares are rectangles. This shape is a square.", options: { A: "It is a rectangle", B: "It is a circle", C: "It has no sides", D: "It is a triangle" }, correctOption: "A" },
      { id: "apt_21", type: "MCQ", promptText: "If a clock shows 3:00, what is the angle between the hands?", options: { A: "0 degrees", B: "30 degrees", C: "90 degrees", D: "180 degrees" }, correctOption: "C" },
      { id: "apt_22", type: "MCQ", promptText: "Choose the odd one out.", options: { A: "Red", B: "Blue", C: "Green", D: "Triangle" }, correctOption: "D" },
      { id: "apt_23", type: "MCQ", promptText: "Find the next letter: Z, X, V, T, ?", options: { A: "R", B: "S", C: "U", D: "Q" }, correctOption: "A" },
      { id: "apt_24", type: "MCQ", promptText: "Which number completes the pattern? 2, 5, 10, 17, ?", options: { A: "24", B: "26", C: "28", D: "30" }, correctOption: "B" },
      { id: "apt_25", type: "MCQ", promptText: "If the word \"DOG\" is coded as \"EPH\", then \"CAT\" is coded as:", options: { A: "DBU", B: "DBT", C: "DPU", D: "CBU" }, correctOption: "A" },
      { id: "apt_26", type: "MCQ", promptText: "Choose the word that best fits: Hot is to Cold as Up is to ?", options: { A: "Down", B: "Left", C: "Right", D: "Over" }, correctOption: "A" },
      { id: "apt_27", type: "MCQ", promptText: "Find the next number: 100, 50, 25, 12.5, ?", options: { A: "6.25", B: "7.5", C: "8.25", D: "10" }, correctOption: "A" },
      { id: "apt_28", type: "MCQ", promptText: "Which word is a noun?", options: { A: "Run", B: "Blue", C: "Happiness", D: "Quickly" }, correctOption: "C" },
      { id: "apt_29", type: "MCQ", promptText: "Choose the best answer: A triangle has how many corners?", options: { A: "2", B: "3", C: "4", D: "5" }, correctOption: "B" },
      { id: "apt_30", type: "MCQ", promptText: "Find the next number: 7, 14, 28, 56, ?", options: { A: "63", B: "70", C: "98", D: "112" }, correctOption: "D" },
      { id: "apt_31", type: "MCQ", promptText: "If all roses are flowers and some flowers fade, then some roses:", options: { A: "Fade", B: "Are blue", C: "Are trees", D: "Are animals" }, correctOption: "A" },
      { id: "apt_32", type: "MCQ", promptText: "Which is the next even number after 48?", options: { A: "49", B: "50", C: "51", D: "52" }, correctOption: "B" },
      { id: "apt_33", type: "MCQ", promptText: "How many dots are shown?", options: { A: "4", B: "5", C: "6", D: "7" }, correctOption: "B" },
      { id: "apt_34", type: "MCQ", promptText: "If it is raining, the ground is wet. It is raining. Therefore:", options: { A: "The ground is wet", B: "The ground is dry", C: "The sun is out", D: "It is snowing" }, correctOption: "A" },
      { id: "apt_35", type: "MCQ", promptText: "Choose the odd one out.", options: { A: "Square", B: "Rectangle", C: "Circle", D: "Triangle" }, correctOption: "C" },
      { id: "apt_36", type: "MCQ", promptText: "Find the next number: 4, 7, 10, 13, ?", options: { A: "15", B: "16", C: "17", D: "18" }, correctOption: "C" },
      { id: "apt_37", type: "MCQ", promptText: "Which word is opposite of \"expand\"?", options: { A: "Grow", B: "Shrink", C: "Open", D: "Increase" }, correctOption: "B" },
      { id: "apt_38", type: "MCQ", promptText: "Choose the best answer: 3 is to 9 as 4 is to ?", options: { A: "12", B: "14", C: "16", D: "18" }, correctOption: "C" },
      { id: "apt_39", type: "MCQ", promptText: "If a=1, b=2, c=3, what is d?", options: { A: "3", B: "4", C: "5", D: "6" }, correctOption: "B" },
      { id: "apt_40", type: "MCQ", promptText: "Which number is missing? 2, 3, 5, 8, 12, ?", options: { A: "15", B: "16", C: "17", D: "18" }, correctOption: "C" },
      { id: "apt_41", type: "MCQ", promptText: "Choose the word that completes: Hand is to Glove as Foot is to ?", options: { A: "Hat", B: "Sock", C: "Ring", D: "Belt" }, correctOption: "B" },
      { id: "apt_42", type: "MCQ", promptText: "Which letter comes next? B, E, H, K, ?", options: { A: "L", B: "M", C: "N", D: "O" }, correctOption: "B" },
      { id: "apt_43", type: "MCQ", promptText: "If 2 + 2 = 4 and 3 + 3 = 6, then 4 + 4 = ?", options: { A: "6", B: "7", C: "8", D: "9" }, correctOption: "C" },
      { id: "apt_44", type: "MCQ", promptText: "Choose the odd one out.", options: { A: "January", B: "February", C: "Monday", D: "March" }, correctOption: "C" },
      { id: "apt_45", type: "MCQ", promptText: "Find the next number: 11, 22, 33, 44, ?", options: { A: "50", B: "55", C: "66", D: "77" }, correctOption: "B" }
    ]
  },
  {
    id: "occupations",
    title: "Occupations",
    subtitle: "Inspiring Professions",
    questions: [
      { id: "job_1", type: "MCQ", promptText: "Which profession is responsible for diagnosing illness?", options: { A: "Architect", B: "Doctor", C: "Chef", D: "Pilot" }, correctOption: "B" },
      { id: "job_2", type: "MCQ", promptText: "Who designs buildings and structures?", options: { A: "Engineer", B: "Architect", C: "Biologist", D: "Designer" }, correctOption: "B" },
      { id: "job_3", type: "MCQ", promptText: "Which job involves flying airplanes?", options: { A: "Mechanic", B: "Pilot", C: "Sailor", D: "Driver" }, correctOption: "B" },
      { id: "job_4", type: "MCQ", promptText: "Who writes code for software and apps?", options: { A: "Programmer", B: "Teacher", C: "Nurse", D: "Chef" }, correctOption: "A" },
      { id: "job_5", type: "MCQ", promptText: "Which profession studies plants and animals?", options: { A: "Geologist", B: "Biologist", C: "Astronomer", D: "Historian" }, correctOption: "B" },
      { id: "job_6", type: "MCQ", promptText: "Who is trained to fight fires?", options: { A: "Police Officer", B: "Firefighter", C: "Paramedic", D: "Lifeguard" }, correctOption: "B" },
      { id: "job_7", type: "MCQ", promptText: "Which job helps people recover movement after injury?", options: { A: "Dentist", B: "Physical Therapist", C: "Pharmacist", D: "Surgeon" }, correctOption: "B" },
      { id: "job_8", type: "MCQ", promptText: "Who writes and edits news stories?", options: { A: "Journalist", B: "Lawyer", C: "Accountant", D: "Engineer" }, correctOption: "A" },
      { id: "job_9", type: "MCQ", promptText: "Which profession protects the public and enforces laws?", options: { A: "Judge", B: "Police Officer", C: "Paramedic", D: "Detective" }, correctOption: "B" },
      { id: "job_10", type: "MCQ", promptText: "Who studies the stars and planets?", options: { A: "Astronomer", B: "Geographer", C: "Chemist", D: "Physicist" }, correctOption: "A" },
      { id: "job_11", type: "MCQ", promptText: "Which job designs and builds machines?", options: { A: "Engineer", B: "Plumber", C: "Electrician", D: "Carpenter" }, correctOption: "A" },
      { id: "job_12", type: "MCQ", promptText: "Who creates lessons and teaches students?", options: { A: "Teacher", B: "Trainer", C: "Coach", D: "Tutor" }, correctOption: "A" },
      { id: "job_13", type: "MCQ", promptText: "Which profession takes care of teeth?", options: { A: "Dentist", B: "Optometrist", C: "Vet", D: "Pediatrician" }, correctOption: "A" },
      { id: "job_14", type: "MCQ", promptText: "Who prepares food in restaurants?", options: { A: "Baker", B: "Chef", C: "Server", D: "Barista" }, correctOption: "B" },
      { id: "job_15", type: "MCQ", promptText: "Which job focuses on animal health?", options: { A: "Vet", B: "Zoologist", C: "Farmer", D: "Trainer" }, correctOption: "A" },
      { id: "job_16", type: "MCQ", promptText: "Who checks financial records for accuracy?", options: { A: "Accountant", B: "Banker", C: "Analyst", D: "Broker" }, correctOption: "A" },
      { id: "job_17", type: "MCQ", promptText: "Which profession builds and repairs electrical systems?", options: { A: "Electrician", B: "Mechanic", C: "Plumber", D: "Carpenter" }, correctOption: "A" },
      { id: "job_18", type: "MCQ", promptText: "Who helps people with legal advice?", options: { A: "Judge", B: "Lawyer", C: "Clerk", D: "Bailiff" }, correctOption: "B" },
      { id: "job_19", type: "MCQ", promptText: "Which job studies Earth's rocks and minerals?", options: { A: "Geologist", B: "Ecologist", C: "Meteorologist", D: "Botanist" }, correctOption: "A" },
      { id: "job_20", type: "MCQ", promptText: "Who creates art using paint or sculpture?", options: { A: "Designer", B: "Artist", C: "Actor", D: "Composer" }, correctOption: "B" },
      { id: "job_21", type: "MCQ", promptText: "Which profession captures photographs?", options: { A: "Photographer", B: "Reporter", C: "Producer", D: "Director" }, correctOption: "A" },
      { id: "job_22", type: "MCQ", promptText: "Who treats patients in emergencies?", options: { A: "Surgeon", B: "Paramedic", C: "Nurse", D: "Therapist" }, correctOption: "B" },
      { id: "job_23", type: "MCQ", promptText: "Which job designs clothing and fashion?", options: { A: "Stylist", B: "Fashion Designer", C: "Tailor", D: "Model" }, correctOption: "B" },
      { id: "job_24", type: "MCQ", promptText: "Who directs a movie or TV show?", options: { A: "Producer", B: "Director", C: "Editor", D: "Screenwriter" }, correctOption: "B" },
      { id: "job_25", type: "MCQ", promptText: "Which profession studies weather?", options: { A: "Astronomer", B: "Meteorologist", C: "Climatologist", D: "Geographer" }, correctOption: "B" },
      { id: "job_26", type: "MCQ", promptText: "Who manages the day-to-day operations of a company?", options: { A: "CEO", B: "Manager", C: "Analyst", D: "Consultant" }, correctOption: "B" },
      { id: "job_27", type: "MCQ", promptText: "Which job helps people buy and sell homes?", options: { A: "Broker", B: "Realtor", C: "Accountant", D: "Appraiser" }, correctOption: "B" },
      { id: "job_28", type: "MCQ", promptText: "Who builds furniture and structures from wood?", options: { A: "Carpenter", B: "Plumber", C: "Mason", D: "Welder" }, correctOption: "A" },
      { id: "job_29", type: "MCQ", promptText: "Which profession creates music?", options: { A: "Composer", B: "Painter", C: "Writer", D: "Actor" }, correctOption: "A" },
      { id: "job_30", type: "MCQ", promptText: "Who takes care of patients in hospitals?", options: { A: "Nurse", B: "Pharmacist", C: "Therapist", D: "Dentist" }, correctOption: "A" },
      { id: "job_31", type: "MCQ", promptText: "Which job studies human behavior and mind?", options: { A: "Psychologist", B: "Sociologist", C: "Anthropologist", D: "Neurologist" }, correctOption: "A" },
      { id: "job_32", type: "MCQ", promptText: "Who designs logos and brand visuals?", options: { A: "Graphic Designer", B: "Photographer", C: "Editor", D: "Writer" }, correctOption: "A" },
      { id: "job_33", type: "MCQ", promptText: "Which profession prepares medicines?", options: { A: "Pharmacist", B: "Nurse", C: "Surgeon", D: "Dentist" }, correctOption: "A" },
      { id: "job_34", type: "MCQ", promptText: "Who fixes cars and engines?", options: { A: "Mechanic", B: "Engineer", C: "Driver", D: "Pilot" }, correctOption: "A" },
      { id: "job_35", type: "MCQ", promptText: "Which job is responsible for training athletes?", options: { A: "Coach", B: "Trainer", C: "Referee", D: "Scout" }, correctOption: "A" },
      { id: "job_36", type: "MCQ", promptText: "Who studies past events and civilizations?", options: { A: "Historian", B: "Linguist", C: "Archaeologist", D: "Sociologist" }, correctOption: "A" },
      { id: "job_37", type: "MCQ", promptText: "Which profession writes books and stories?", options: { A: "Writer", B: "Poet", C: "Editor", D: "Publisher" }, correctOption: "A" },
      { id: "job_38", type: "MCQ", promptText: "Who assists people with hearing loss?", options: { A: "Audiologist", B: "Optometrist", C: "Dermatologist", D: "Dietitian" }, correctOption: "A" },
      { id: "job_39", type: "MCQ", promptText: "Which job plans and builds roads and bridges?", options: { A: "Civil Engineer", B: "Surveyor", C: "Architect", D: "Contractor" }, correctOption: "A" },
      { id: "job_40", type: "MCQ", promptText: "Who uses maps and GPS to guide travel?", options: { A: "Navigator", B: "Pilot", C: "Driver", D: "Guide" }, correctOption: "A" },
      { id: "job_41", type: "MCQ", promptText: "Which profession works with space missions?", options: { A: "Astronaut", B: "Pilot", C: "Engineer", D: "Scientist" }, correctOption: "A" },
      { id: "job_42", type: "MCQ", promptText: "Who specializes in skin health?", options: { A: "Dermatologist", B: "Cardiologist", C: "Orthopedist", D: "Neurologist" }, correctOption: "A" },
      { id: "job_43", type: "MCQ", promptText: "Which job plans events and schedules?", options: { A: "Coordinator", B: "Planner", C: "Organizer", D: "All of these" }, correctOption: "D" },
      { id: "job_44", type: "MCQ", promptText: "Who designs video games and interactive media?", options: { A: "Game Designer", B: "Animator", C: "Programmer", D: "Producer" }, correctOption: "A" },
      { id: "job_45", type: "MCQ", promptText: "Which profession manages money and budgets?", options: { A: "Financial Analyst", B: "Coach", C: "Editor", D: "Scientist" }, correctOption: "A" }
    ]
  },
  {
    id: "objects_concepts",
    title: "Objects & Concepts",
    subtitle: "Wheels, Wings, and More • Trip Through Town",
    questions: [
      { id: "obj_1", type: "MCQ", promptText: "Which object is used to tell time?", options: { A: "Compass", B: "Clock", C: "Thermometer", D: "Barometer" }, correctOption: "B" },
      { id: "obj_2", type: "MCQ", promptText: "Which vehicle uses wings to fly?", options: { A: "Boat", B: "Train", C: "Airplane", D: "Car" }, correctOption: "C" },
      { id: "obj_3", type: "MCQ", promptText: "What do wheels help reduce?", options: { A: "Friction", B: "Heat", C: "Light", D: "Sound" }, correctOption: "A" },
      { id: "obj_4", type: "MCQ", promptText: "Which item is used to cross a river safely?", options: { A: "Bridge", B: "Tunnel", C: "Ladder", D: "Fence" }, correctOption: "A" },
      { id: "obj_5", type: "MCQ", promptText: "Which object is used to write on paper?", options: { A: "Spoon", B: "Pen", C: "Ruler", D: "Hammer" }, correctOption: "B" },
      { id: "obj_6", type: "MCQ", promptText: "What powers a traditional bicycle?", options: { A: "Fuel", B: "Electricity", C: "Human pedaling", D: "Wind" }, correctOption: "C" },
      { id: "obj_7", type: "MCQ", promptText: "Which object is used to cook food with heat?", options: { A: "Oven", B: "Freezer", C: "Fan", D: "Vacuum" }, correctOption: "A" },
      { id: "obj_8", type: "MCQ", promptText: "Which object helps you see far away?", options: { A: "Microscope", B: "Telescope", C: "Thermometer", D: "Compass" }, correctOption: "B" },
      { id: "obj_9", type: "MCQ", promptText: "Which item is used to protect your head while biking?", options: { A: "Helmet", B: "Gloves", C: "Boots", D: "Cape" }, correctOption: "A" },
      { id: "obj_10", type: "MCQ", promptText: "Which city building is used for borrowing books?", options: { A: "Library", B: "Bakery", C: "Hospital", D: "Museum" }, correctOption: "A" },
      { id: "obj_11", type: "MCQ", promptText: "Which tool is used to tighten bolts?", options: { A: "Hammer", B: "Wrench", C: "Saw", D: "Brush" }, correctOption: "B" },
      { id: "obj_12", type: "MCQ", promptText: "Which vehicle runs on rails in a city?", options: { A: "Tram", B: "Boat", C: "Bike", D: "Truck" }, correctOption: "A" },
      { id: "obj_13", type: "MCQ", promptText: "What do wings help birds do?", options: { A: "Swim", B: "Fly", C: "Dig", D: "Hide" }, correctOption: "B" },
      { id: "obj_14", type: "MCQ", promptText: "Which object tells you direction?", options: { A: "Clock", B: "Compass", C: "Camera", D: "Scale" }, correctOption: "B" },
      { id: "obj_15", type: "MCQ", promptText: "Which place in town is used to treat sick people?", options: { A: "School", B: "Hospital", C: "Stadium", D: "Post Office" }, correctOption: "B" },
      { id: "obj_16", type: "MCQ", promptText: "Which object is used to take photos?", options: { A: "Camera", B: "Radio", C: "Speaker", D: "Printer" }, correctOption: "A" },
      { id: "obj_17", type: "MCQ", promptText: "Which vehicle is powered by an engine and carries passengers in a city?", options: { A: "Bus", B: "Scooter", C: "Bike", D: "Skateboard" }, correctOption: "A" },
      { id: "obj_18", type: "MCQ", promptText: "Which object is used to measure temperature?", options: { A: "Thermometer", B: "Ruler", C: "Scale", D: "Compass" }, correctOption: "A" },
      { id: "obj_19", type: "MCQ", promptText: "Which tool is used to cut wood?", options: { A: "Saw", B: "Wrench", C: "Screwdriver", D: "Pliers" }, correctOption: "A" },
      { id: "obj_20", type: "MCQ", promptText: "Which place sells groceries in town?", options: { A: "Bakery", B: "Supermarket", C: "Library", D: "Post Office" }, correctOption: "B" },
      { id: "obj_21", type: "MCQ", promptText: "Which object helps cars stop?", options: { A: "Brakes", B: "Pedals", C: "Mirrors", D: "Seats" }, correctOption: "A" },
      { id: "obj_22", type: "MCQ", promptText: "Which object is used to mail letters?", options: { A: "Mailbox", B: "Locker", C: "Chimney", D: "Drawer" }, correctOption: "A" },
      { id: "obj_23", type: "MCQ", promptText: "Which machine helps clean floors?", options: { A: "Vacuum", B: "Microwave", C: "Toaster", D: "Fan" }, correctOption: "A" },
      { id: "obj_24", type: "MCQ", promptText: "Which object is used to unlock doors?", options: { A: "Key", B: "Pin", C: "Clip", D: "String" }, correctOption: "A" },
      { id: "obj_25", type: "MCQ", promptText: "Which place in town sends letters and packages?", options: { A: "Bank", B: "Post Office", C: "Gym", D: "Theater" }, correctOption: "B" },
      { id: "obj_26", type: "MCQ", promptText: "Which object is used to play music?", options: { A: "Speaker", B: "Blender", C: "Printer", D: "Toaster" }, correctOption: "A" },
      { id: "obj_27", type: "MCQ", promptText: "Which vehicle is designed to travel underground in cities?", options: { A: "Subway", B: "Bus", C: "Ferry", D: "Taxi" }, correctOption: "A" },
      { id: "obj_28", type: "MCQ", promptText: "Which object is used to lift heavy items?", options: { A: "Crane", B: "Mop", C: "Bucket", D: "Broom" }, correctOption: "A" },
      { id: "obj_29", type: "MCQ", promptText: "Which object is used to light a room?", options: { A: "Lamp", B: "Fan", C: "Clock", D: "Radio" }, correctOption: "A" },
      { id: "obj_30", type: "MCQ", promptText: "Which place in town is used for sports games?", options: { A: "Stadium", B: "Museum", C: "Library", D: "Theater" }, correctOption: "A" },
      { id: "obj_31", type: "MCQ", promptText: "Which tool is used to drive screws?", options: { A: "Screwdriver", B: "Hammer", C: "Pliers", D: "Wrench" }, correctOption: "A" },
      { id: "obj_32", type: "MCQ", promptText: "Which object is used to store cold food?", options: { A: "Oven", B: "Refrigerator", C: "Toaster", D: "Kettle" }, correctOption: "B" },
      { id: "obj_33", type: "MCQ", promptText: "Which vehicle is powered by wind on water?", options: { A: "Sailboat", B: "Submarine", C: "Ferry", D: "Canoe" }, correctOption: "A" },
      { id: "obj_34", type: "MCQ", promptText: "Which object helps you cross a street safely?", options: { A: "Crosswalk", B: "Driveway", C: "Garage", D: "Alley" }, correctOption: "A" },
      { id: "obj_35", type: "MCQ", promptText: "Which object is used to pay for items?", options: { A: "Wallet", B: "Notebook", C: "Backpack", D: "Helmet" }, correctOption: "A" },
      { id: "obj_36", type: "MCQ", promptText: "Which place in town helps you withdraw money?", options: { A: "Bank", B: "Clinic", C: "School", D: "Park" }, correctOption: "A" },
      { id: "obj_37", type: "MCQ", promptText: "Which machine is used to wash clothes?", options: { A: "Washing Machine", B: "Dishwasher", C: "Dryer", D: "Mixer" }, correctOption: "A" },
      { id: "obj_38", type: "MCQ", promptText: "Which object is used to see your reflection?", options: { A: "Mirror", B: "Window", C: "Screen", D: "Lens" }, correctOption: "A" },
      { id: "obj_39", type: "MCQ", promptText: "Which city feature controls traffic flow?", options: { A: "Traffic Light", B: "Street Sign", C: "Speed Bump", D: "Sidewalk" }, correctOption: "A" },
      { id: "obj_40", type: "MCQ", promptText: "Which object keeps rain off your head?", options: { A: "Umbrella", B: "Scarf", C: "Boots", D: "Belt" }, correctOption: "A" },
      { id: "obj_41", type: "MCQ", promptText: "Which place in town shows movies?", options: { A: "Cinema", B: "Museum", C: "Library", D: "Gym" }, correctOption: "A" },
      { id: "obj_42", type: "MCQ", promptText: "Which object helps you climb to high places?", options: { A: "Ladder", B: "Rope", C: "Net", D: "Ramp" }, correctOption: "A" },
      { id: "obj_43", type: "MCQ", promptText: "Which object is used to carry groceries?", options: { A: "Basket", B: "Envelope", C: "Wallet", D: "Book" }, correctOption: "A" },
      { id: "obj_44", type: "MCQ", promptText: "Which vehicle is used to deliver packages quickly in town?", options: { A: "Delivery Van", B: "Sailboat", C: "Train", D: "Cable Car" }, correctOption: "A" },
      { id: "obj_45", type: "MCQ", promptText: "Which place in town helps people learn?", options: { A: "School", B: "Cafe", C: "Stadium", D: "Garage" }, correctOption: "A" }
    ]
  }
];

export const subscriptionTiers = {
  FREE: {
    id: "FREE",
    name: "Free",
    price: 0,
    priceLabel: "Free Forever",
    description: "Perfect for casual play",
    features: [
      "2 free packs",
      "No custom packs",
      "10 participants per session",
      "All core game modes",
      "Basic lifelines",
      "Community support"
    ],
    limits: {
      maxPacks: 0,
      maxParticipants: 10,
      customBranding: false,
      analytics: false,
      prioritySupport: false
    }
  },
  PRO: {
    id: "PRO",
    name: "Pro",
    price: 9.99,
    priceLabel: "$9.99/month",
    description: "For serious hosts",
    features: [
      "5 custom packs",
      "Live sessions",
      "100 participants per session",
      "Advanced analytics",
      "Priority email support",
      "Export game data"
    ],
    limits: {
      maxPacks: 5,
      maxParticipants: 100,
      customBranding: true,
      analytics: true,
      prioritySupport: false
    },
    badge: "Most Popular"
  },
  ENTERPRISE: {
    id: "ENTERPRISE",
    name: "Enterprise",
    price: 49.99,
    priceLabel: "$49.99/month",
    description: "For organizations",
    features: [
      "100 custom packs",
      "Live sessions",
      "Unlimited participants",
      "Advanced analytics & reporting",
      "24/7 priority support",
      "Dedicated account manager",
      "Global leaderboard access",
      "Custom branding & themes"
    ],
    limits: {
      maxPacks: 100,
      maxParticipants: Infinity,
      customBranding: true,
      analytics: true,
      prioritySupport: true
    }
  }
};
